// <auto-generated />
namespace WaReentryResourceGuide.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SingleCounty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SingleCounty));
        
        string IMigrationMetadata.Id
        {
            get { return "201707260125428_SingleCounty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
